import '@/app/globals.scss';

import { GeistSans } from 'geist/font/sans';

import AppLayout from '@/components/layout/AppLayout';

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${GeistSans.variable} ${GeistSans.className} bg-gray-900 ${GeistSans.variable} antialiased`}
        >
        <AppLayout>
            {children}
        </AppLayout>
        </body>
        </html>
    );
}
